name: Go Format Check

on: [pull_request]
jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: go fmt
        run: go fmt .
      - name: diff
        run: git diff --exit-code
